[workspace]
resolver = "2"
members = [
    "android/translations-converter",
    "mullvad-daemon",
    "mullvad-cli",
    "mullvad-setup",
    "mullvad-problem-report",
    "mullvad-jni",
    "mullvad-paths",
    "mullvad-relay-selector",
    "mullvad-types",
    "mullvad-api",
    "mullvad-exclude",
    "talpid-openvpn-plugin",
    "talpid-core",
    "talpid-dbus",
    "talpid-platform-metadata",
    "talpid-relay-config-client",
    "talpid-time",
    "mullvad-management-interface",
    "tunnel-obfuscation",
]

[profile.release]
opt-level = 3
lto = true
